### ISSUE TITLE
Keep server upload creating duplicate objects

### ISSUE THREAD

**Issue by erussey** [emory-libraries/TheKeep#11]
The Keep is currently having issues with moving image files being loaded through the server. Note that we're currently holding off loading through this method in order to avoid duplicate objects, so this is a priority issue for us. The following is a description from Trey about what's going on along with some timestamps (on 2/9) so you can look in the logs: 

I just saw the thing I was telling you about happen. Here are the notes I made. (The first few I uploaded went in fine. Also, these bags are all very close to the same size, around 8 GB, so I don’t think file size is a factor.) These are in this collection: https://keep.library.emory.edu/admin/search/?keyword=John%20Reilly%20Samuel%20Beckett%20audiovisual%20material 10:57 a.m. Began ingest of Reilly_035. Gateway Time-out at 11:11. Checked index (still out of order), not there. Checked again at 11:18. Now Reilly_035 is in there twice. It’s also no longer on the staging server. When I’d get these errors in the past, but the bag still went in anyway, sometimes I would find that the bag had not been deleted off the server. Then I’d have to go in and delete myself. Now it’s like the opposite is happening.

This is documented in INC02866914 as well.

**Comment by erussey** [comment]
@alexBLR : This issue has not been resolved.  I asked Trey to check again, and things are still being ingested twice.  Here's his log report:
2/23/2018
2:57 pm - Began ingest of Reilly_036
3:01 - different error than usual: Chrome says: This page isn’t working
keep.library.emory.edu didn’t send any data.
ERR_EMPTY_RESPONSE
 
3:11 - Reilly_036 showed up in index
3:21 - Checked repeatedly to see if bag went in a second time, no
3:22 - Began ingest of Reilly_037.  Noted that Reilly_036 did not get deleted from server.
3:28 - Ingest of Reilly_037 successful
3:29 - Began ingest of Reilly_038
3:39 - Ingest successful
3:40 - Began ingest of Reilly_039
3:49 - Ingest successful
3:50 - Began ingest of Reilly_040
3:58 - Ingest successful
4:00 - Began ingest of 1256_Tape_1
4:11 - Gateway Time-out error
--still not showing up as of 4:31, left work
--checked again that evening, 1256_tape_1 is in there twice.

**Comment by alexBLR** [comment]
@erussey What happened after 4:11 Gateway timeout error. Did he just leave the error hanging, clicked back button, reuploaded?

**Comment by erussey** [comment]
@alexBLR : He went back to the keep dashboard (keep.library.emory.edu) by taking off the end of the URL and then hitting enter to return to the dashboard.
