### ISSUE TITLE
Update Keep mimetype library

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#14]
Submitted by Elizabeth Roke on August 7, 2019

We have discovered that the Keep is running an outdated mimetype library, which may be causing some ingest issues for us (which are ongoing with video).  Would it be possible for Mark to run an update to the python module or library that the Keep uses to validate mimetype?  It looks like we'd need to update "python magic" to the latest version.  If we could try this in test first, we have a couple of video files that have been rejected from the Keep but validate in an updated version of mimetype validation.

I suspect that this would be an easy fix to helping us ingest video content that cannot currently be ingested (but is valid).

**Comment by rotated8** [comment]
Closing- this ticket is so old the work has already been done, or it isn't necessary.
