### ISSUE TITLE
OpenEmory: upadate banner on all website pages with new Emory Library logo

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#15]
The OpenEmory website needs to be updated with the new Emory Library logo in place of the Emory LITS logo. Artwork for the new logo can be found on box at https://emory.app.box.com/folder/127843707123?s=uhwpkxnh2g85qvxciv9lgrxhsxnwieeu

**Comment by libdgg** [comment]
Here is the PNG reversed image (you may not be able to see it inline here):
![ELib_OpenEmory_hz_rv.png](https://images.zenhubusercontent.com/5c0ec309cd03b2349870e625/14c74ebf-c240-4060-a80e-74588b31410e)

**Comment by rotated8** [comment]
This is done.
