### ISSUE TITLE
RabbitMQ - restart cron job

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#17]
RabbitMQ restart - it queues up tasks for things to be done asynchronously. It does this for multiple applications (Keep, Finding Aids, Open Emory).
lives repoprd001
cron job
3am restart (that is time for lowest activity)

NOTES:
what happens if this gets restarted with active requests in the queue - nothing, they just wait until continue.
no other tools on the repoprd001 server
eulindexer could be the next thing we could look at restarting.
zo can create a list for beth on what needs to be restarted and when. (service, where it lives)

**Comment by jcrompton42** [comment]
created /etc/cron.d/services-restarts.crontab on repoprd001 to restart at 3:03 pm
