### ISSUE TITLE
Firewall and IP Addresses

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#32]
[JH] I need to get the name and I/P address of the application servers that use these databases.  I’ll open Emory firewall rule exceptions to allow them to reach the new RDS.  Previous migration/upgrade projects have reported the best performance when the application server is also in AWS.  Please consider this as an opportunity to move your applications to the cloud too.

**Comment by rotated8** [comment]
Server names and ip addresses are in the legacy application spreadsheet.

**Comment by rotated8** [comment]
[Link to spreadsheet](https://emory.sharepoint.com/:x:/r/sites/EULLTDS/Shared%20Documents/Departments%20and%20Units/Technology%20Development%20and%20Operations/Inventories/Software%20Development%20Applications%20Inventory.xlsx?d=w826d1ab6fcb744a3b86012cd4ab24a3f&csf=1&web=1&e=bmZwmj)
