### ISSUE TITLE
Verify Staffing 2/13 - 5/26

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#39]
Staffing and Roles:

**LTDS Technology Team** 

- Doug Goans (Project Manager)  
- Collin Brittle (Tech Lead and Application Manager) 
- Alex Cooper (Middleware Manager) 
- Kaeln Bowater-Skelly (Middleware) 
- Beth Crompton (Middleware) 
- Alex Zotov (Application) 

**OIT: ORACLE** 

- Saleem Durrani (OIT - manage the MySQL database upgrade/migration - same for Oracle) 
- Jocelyn Ramirez (PSMO Project Manager oracle)
- Naiqi Li (OIT oracle dba) 

**OIT: MYSQL** 
- Saleem Durrani (OIT - manage the MySQL database upgrade/migration - same for Oracle) 
- Jim Houghton (OIT DBA) - upgrading mysql 5 databases 

**Product Stakeholders: Fedora/Oracle**
- OpenEmory- Bailey, Jody; Shannon, Kylie; Townes, Jenny; Porter, Emily
- The Keep- Fisher, Katherine; Michaelis, Kathryn; Rao, Nina; Carrie Hintz
- Digitized Books- Fenton, Kyle

**Product Stakeholders: MySQL**
- OpenEmory- Bailey, Jody; Shannon, Kylie; Townes, Jenny; Porter, Emily
- The Keep- Fisher, Katherine; Michaelis, Kathryn; Rao, Nina; Carrie Hintz
- emorylib.info- Bragg, Colin
- PidMan- Kat Hart

**Comment by libdgg** [comment]
Project Roles  - Total Project Hours  - Total FTE Count  ( 15 week effort )
February 13 - May 26

**LTDS Project Manager**  

- (LTDS staff member serving as project manager) = Doug Goans 
- 30 
- 1 staff at 2 hours per week 

**OIT Database Team** 

- (to assist with consultation or configuration related to migration of content). = Saleem, Jocelyn, Jim Houghton, Kevin Chen 
- 75 
- 5 staff at 1 hour per week (Varies based on needs for consultation) 

**LTDS System Administrators and Technical Leads** 

- (Design solution, project tasks with OIT technical/db leads, implementing migration, configurations, conducting risk mitigation actions) = Collin, Alex, Beth, Kaeln, Zo 
- 600 
- Approximately 5 staff at 8 hours per week

 

**LTDS Managers** 

- (Stakeholder representatives, content governance planning, operational support planning) = LTDS Managers Group (Emily, Kathryn, Tricia, Tiffany, Elizabeth, Alex, Collin, Cari, Doug) 
- 40 
- 10 staff members .25 hours/week 

**LTDS Leadership** 

- (Project oversight, fiscal management, approvals) = LTDS-L Group (Rosalyn, Cari, Doug) 
- 40 
- 3 staff members at .25 hours/week (Varies based on requirements for review and input of project deliverables)  

**EUL Database Users / Stakeholders** 

- (will be identified in planning) 
- QA and Testing 

**Total Hours**   
- 785 hours (estimate) 
- 25 – 30 people (estimate)

**Comment by libdgg** [comment]
ACTION; CB confirm people for testing.
ACTION: DG schedule LTDS team meeting.

**Comment by rotated8** [comment]
Previously contacted stakeholders are as follows.

Fedora Stakeholders: 
OpenEmory- Bailey, Jody; Shannon, Kylie; Townes, Jenny
The Keep- Fisher, Katherine; Michaelis, Kathryn; Rao, Nina
Digitized Books- Fenton, Kyle

MySQL Stakeholders:
OpenEmory- Bailey, Jody; Shannon, Kylie; Townes, Jenny
The Keep- Fisher, Katherine; Michaelis, Kathryn; Rao, Nina
emorylib.info- Bragg, Colin
PidMan- None

Hart, Kat to be added for PidMan, Porter, Emily to be added for OpenEmory.

**Comment by rotated8** [comment]
Hintz, Carrie will take over for Fisher, Katherine while she is out.
