### ISSUE TITLE
Data Dumps

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#43]
Get data dumps from Jim and confirm who? has access and next steps.

**Comment by libdgg** [comment]
ACTION: @rotated8 Collin please update this ticket with any links to the dumps, verifications or next steps.

**Comment by jcrompton42** [comment]
The dumps are now located in s3 bucket decommissioned-database-dumps in AWS account 70 and region US East 1.

**Comment by libdgg** [comment]
ACCESS: Anyone who has access to the DLP AWS account should be able to access the data dumps.

**Comment by libdgg** [comment]
ACTION: BC will setup auto reminders for slack and email and policy on AWS

**Comment by jcrompton42** [comment]
Slack and the calendar will remind us on Feb 27 2024 that these data dumps will be deleted March 1 2024, and a lifecycle rule has been created on the aws bucket to delete the objects on March 1 2024
