### ISSUE TITLE
Documenting Databases and Associated Servers

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#45]
do we plan to document all of these databases and their associated servers as part of this move?
ANSWER: CB has a todo to start that work for a meeting with the database team next week. We can continue that forward as a deliverable for closeout. CB has spreadsheet

**Comment by libdgg** [comment]
ACTION: CB will add a link to the spreadsheet then close this ticket

**Comment by rotated8** [comment]
[Spreadsheet](https://emory.sharepoint.com/:x:/r/sites/EULLTDS/Shared%20Documents/Departments%20and%20Units/Technology%20Development%20and%20Operations/Inventories/Software%20Development%20Applications%20Inventory.xlsx?d=w826d1ab6fcb744a3b86012cd4ab24a3f&csf=1&web=1&e=2xCZ6j)
