### ISSUE TITLE
Cost Estimates and Savings

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#46]
This ticket will deliver the operating cost estimates (and final) as well as any cost savings information to the AUL for LTDS.

Are there any costs (or changes to costs) that we need to address in the oracle db migration project (i.e. speedtype provision etc.)

[SD]: Yes. For the billing we tagged every on-prem VM or the RDS instance with the concern application speed type. The system team also charges a flat monthly fee or sysadmin charge of $158 every month. Please reach out to the System team (Steve Siegelman) if you want to know the exact cost for your on-prem infrastructure.

**Comment by libdgg** [comment]
ACTION: Doug reached out to Steve S. on 2023-02-24 to confirm costs, any increase and if he needs a speedtype.

**Comment by libdgg** [comment]
@kbowaterskelly please collect estimates on costs and provide to Rosalyn for approval. I'll add anything I hear from Steve S.

**Comment by libdgg** [comment]
Check mysoft for speedtype 9470.
There will be a cost increase temporarily as we are going from 1 oracle server to 2.

**Comment by libdgg** [comment]
Consider merging cost tickets into a single cost effort.

**Comment by kbowaterskelly** [comment]
What is the name of the server we are duplicating?

**Comment by kbowaterskelly** [comment]
If it's utilprd001 which is labeled as the keep server, our total cost with sysadmin service, as a duplicate, is 196.46. We are not currently paying for sysadmin service on this server. That means the maximum total cost is $200 or below for the new server. We may incur costs on the old server because we may have needed DBA service, at a cost of $156.04.

**Comment by libdgg** [comment]
Costs are reflected in OIT billing. Expect billing to remain the same or possibly decrease. As far as we are aware there are no upfront costs.

@kbowaterskelly can check on this.

**Comment by libdgg** [comment]
Closing as project work is completed and costs are under $500 and we know how to check if we need to revisit costs operationally  going forward.
