### ISSUE TITLE
ServiceNow Ticket to Delete Databases

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#47]
2023-02-24
Library team,
Please open a ServiceNow ticket and assign it to OIT: Database Support - Tier 3.  Request that I delete the following databases without retaining backups.  Note:  This list includes the findingaids databases that we documented to decommission by July 2023.  If you are not ready for this to be deleted, DO NOT include it in the ServiceNow ticket.

libmysqldev1.cc.emory.edu
- findingaids
- library_information 
- oai38_qas
- pidqas
- rushdie

libmysqlprod1.cc.emory.edu
- emoryit
- emorylits
- etd
- findingaids
- libraryuse
- marbla
- rushdie

 Thank you,
Jim

**Comment by libdgg** [comment]
@jcrompton42 Checking to see if this ticket is closed per the other "Data Dump" ticket or if this ticket needs to remain open for any reason.

**Comment by jcrompton42** [comment]
Leave this ticket open? I still need to create these service now tickets.

**Comment by jcrompton42** [comment]
Ticket INC03988390 created, leaving out findingaids since I don't believe we are ready to decommission that quite yet. Now we can close this out.
