### ISSUE TITLE
Test DB Server

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#49]
BC put connection string in slack
Respond to OIT team to proceed
 - Confirm connection information won't change (if so what it is)
- Confirm downtime
- Provide speedtype for the server

Downtime for copy
Old server deleted

**Comment by jcrompton42** [comment]
accidentally added an openemory comment to this keep ticket, disregard.

**Comment by libdgg** [comment]
Collin will talk to OIT to ensure the old db server is shut down.

**Comment by libdgg** [comment]
Naiqi Li - confirm that the Oracle db for fedora has been shutdown - fedcoqa.
Ask if the legacy fedora database servers are shut down. email sent on 8/18/2023

**Comment by libdgg** [comment]
2023-08-18 Naiqi responded
"Hi Doug, You are correct.  The old fedora servers are shut down.  Both QA and production databases were upgraded to Oracle 19C on the new servers. Thanks, Naiqi"
