### ISSUE TITLE
Keep QA DB Upgrade

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/TheKeep#50]
The Keep is not compatible with MySQL 8.

- [x] Find a library that works with Python 2 and MySQL 8
- [x] Update the Keep to use that library
- [x] Deploy updated app to QA
- [x] Test QA to ensure existing functionality continues to work.

**Comment by jcrompton42** [comment]
I have installed mysql 8 libraries on testkeep (wlibqas002) and contacted the db team about creating a new database

**Comment by alexBLR** [comment]
We contacted and got details about the migrated Keep QA DB. Beth upgraded the server to MySQL 8 and the config for DB. We both tested the application and everything is working successfully.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b60abdcfd705c11a7ac223e0654c8e46dc437ec/Screen%20Shot%202023-08-16%20at%208.24.15%20AM.png)
