### ISSUE TITLE
Video editor screen contains incorrect header text.

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/TheKeep#6]
The text "The physical form or medium of the resource" appears twice in the form. It should only appear after the Form dropdown and not above the Gauge field box. See attached screenshot

**Comment by alexBLR** [comment]
![Screen Shot 2017-06-20 at 1.02.22 PM-1-.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcf72fdbefb001a9aa262/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456f36b7191a379f112294f5d5d5ecc3c455e59eee59b6be4e96625d91819e7c3685625c06e18acb0861bb754b9758b4f87b0bc8348c2b93c37fb99cd1e604a5a45d0b50877b29359c951fc4ae44d50a7133f6aee753e7f4f8653.png)

**Comment by rosy1280** [comment]
[ ] "The physical form or medium of the resource" does not appear about the Gauge field box on the <link>

**Comment by erussey** [comment]
Testing by product owner complete.
