### ISSUE TITLE
Keep Prod

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#61]
Rose Library will need to know when the change will happen.

**Comment by libdgg** [comment]
DG ask Katherine Fisher, Elizabeth Roke and Nina Rao if there is any reason we can't do this upgrade next week (Mon-Thu).  This will be done during business hours.

**Comment by libdgg** [comment]
Katherine responded "Thanks for the heads up. If it’s possible to schedule the update to happen before 10 AM or after 4 PM, that would reduce the impact on researchers using the Keep in the Rose Library reading room. If not, that’s fine too—I’d just like to notify our reading room and instruction staff of the day and time so they can plan around the downtime."

Nina has not responded so far.

@jcrompton42 will schedule a date so we can then let stakeholders know.

**Comment by libdgg** [comment]
Beth will plan this for Thursday before 10am.

**Comment by jcrompton42** [comment]
migrated!
