### ISSUE TITLE
emorylib prod

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#62]
https://emorylib.info/

Colin Bragg will need to know when the change will happen.

**Comment by libdgg** [comment]
DG ask Colin Bragg if there is any reason we can't do this upgrade next week (Mon-Thu).  This will be done during business hours.

**Comment by libdgg** [comment]
Colin would like this to happen Thursday or Friday. @jcrompton42 is looking at Thursday.

**Comment by libdgg** [comment]
Beth will be making a ticket for this today.

**Comment by libdgg** [comment]
Has been migrated. Beth messaged Colin. Beth will close the ticket when Colin says it's good.

**Comment by jcrompton42** [comment]
Collin Bragg says it looks good!
