### ISSUE TITLE
decommission the old prod servers on mysqlprod1 

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#63]

**Comment by kbowaterskelly** [comment]
These are ready to be done but we don't believe they have been decommissioned yet. We may be waiting for stakeholder confirmation.

**Comment by libdgg** [comment]
Hold on inquiring with OIT on this (gives more time just in case stakeholders report something in the coming weeks). Bills usually come in on the 25th or 26th for the previous month. 

Check in with OIT on server decommission in 2 weeks. Confirm that these things won't show up on the bill after November.

**Comment by libdgg** [comment]
on 2023-10-06 Collin put in a ticket to OIT 
[INC04136033
](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D0fb153d887bd35d0fbcd7519dabb3595%26sysparm_stack%3D%26sysparm_view%3D)
The remaining library production databases, and the dev mysql server should all be decommissioned.
Specifically, the production databases are:
digitizedbooks
eulindexer
openemory
pidman

And the dev server is libdbmysqldev1.

**Comment by libdgg** [comment]
the servicenow ticket has been resolved.
