### ISSUE TITLE
Video objects are missing a mimetype in fedora.

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/TheKeep#7]

**Comment by rosy1280** [comment]
is there a mimetype that they need?  is there a way of automatically generating these?

**Comment by rosy1280** [comment]
- [ ] search objects that are video content model; limit to those that don't have a mimetype
- [ ] provide a list of PIDs with no mimetypes
- [ ] run objects through the file characterization process again to recalculate the mimetype
- [ ] re-run the query in bullet 1 to show that the objects have a mimetype

**Comment by alexBLR** [comment]
Identified two pids in prod where the mime type is missing. ['info:fedora/emory:ps7h2/VIDEO', 'info:fedora/emory:ps7j6/VIDEO']

**Comment by alexBLR** [comment]
```
 >>> query = """select ?ds where {?ds <info:fedora/fedora-system:def/view#mimeType> "application/octet-stream" FILTER regex(str(?ds), "VIDEO")}"""
>>> pids = [o['ds'] for o in repo.risearch.sparql_query(query)]
>>> pids
[]

**Comment by erussey** [comment]
@alexBLR : I'm a little confused about this one.  In the original request for this bug (in 2016), Rebecca reported that there were 185 video records in production missing a mimetype.  We've done no work on this bug, so I don't understand why you only found 2.

**Comment by alexBLR** [comment]
@erussey, I remember something about us running it before Rebecca left. I identified only 2 videos.

**Comment by erussey** [comment]
ok @alexBLR .  I've verified both have been fixed.  Testing complete.
