### ISSUE TITLE
Summary report for Keep collections for DLP

### ISSUE THREAD

**Issue by erussey** [emory-libraries/TheKeep#8]

**Comment by erussey** [comment]
@rosy1280 @alexBLR: I need the following reports run on the Keep per a DLP request.  For each collection, I need the following information (by collection)
- [ ] total object count by mimetype (with a total count of the number of objects by mimetype in each collection); we only need to count objects in the "original" datastream
- [ ] total size per collection (calculated size of total of all objects in a collection); we only need to count objects in the "original" datastream
- [ ] access status codes associated with objects in the collection (with a total count of the number of objects in a collection associated with each code); this is located in <rt:accessStatus code="".
- [ ] library the collection is associated with; this is located in <fedora-relsext:isMemberOfCollection rdf:resource="">
- [ ] collection title; this is located in <mods:titleInfo><mods:title>
- [ ] collection number; this is located in <mods:identifier type="local_source_id">

Please provide this report in a CSV file.

**Comment by rosy1280** [comment]
Attached is the excel template the Digital Preservation Group created to help with creating the above reports. 

[Digital Content Inventory - Template.xlsx](https://github.com/emory-libraries/TheKeep/files/1540319/Digital.Content.Inventory.-.Template.xlsx)
